# Generated by Django 5.1.5 on 2025-04-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LargeCategories',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '大カテゴリ',
                'verbose_name_plural': '大カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='MediumCategories',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('parentCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.largecategories')),
            ],
            options={
                'verbose_name': '中カテゴリ',
                'verbose_name_plural': '中カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='SmallCategories',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('parentCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.mediumcategories')),
            ],
            options={
                'verbose_name': '小カテゴリ',
                'verbose_name_plural': '小カテゴリ',
            },
        ),
    ]
