on:
  pull_request:
    branches:
      - develop
      - master

env:
  SECRET_KEY: test
  ALLOWED_HOSTS: 127.0.0.1
  # "True"にしないとDEBUG内がFalseになってしまう
  DEBUG: "True"
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_HOST: 127.0.0.1
      
jobs:

  frontend:

    runs-on: ubuntu-22.04
    container: node:20.10.0-buster-slim

    defaults:
      run:
        working-directory: ./frontend/app

    steps:
      - name: check out repositry
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install 
        run: npm install --legacy-peer-deps

      - name: test
        run: npm run test 

  backend:
    # Postgresのサービスコンテナを設定
    services:
      db:
        # PostgresのDocker imageを使用
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_NAME: ${{ env.POSTGRES_NAME }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        # Postgresより先にDjangoが起動しないようヘルスチェックを使って起動順を制御
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-22.04
    container:
      image: python:3.12-slim

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: check out repositry
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=/usr/local/lib/python3.12/site-packages" >> $GITHUB_ENV

      - name: install 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: test
        run: python3 manage.py test

        env:
          DB_HOST: ${{ env.POSTGRES_HOST }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_USER: ${{ env.POSTGRES_USER }}